<a href="https://colab.research.google.com/github/josueoteiza/arreglos/blob/main/arreglos_ejemplos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A = [20, 15, 12, 11, 8, 4, 1]
maxi = 20
mini = maxi
for i in A:
  if i<mini:
   mini=i
print ("El promedio más bajo es:",mini)
A.remove(mini)
print(A)
suma = 0
for j in A:
  suma+=j
  print (suma)
  print (suma/len(A))

El promedio más bajo es: 1
[20, 15, 12, 11, 8, 4]
20
3.3333333333333335
35
5.833333333333333
47
7.833333333333333
58
9.666666666666666
66
11.0
70
11.666666666666666


In [ ]:
##elemento aleatorio
import random
lenguajes = ["Java", "Python", "C", "Go", "JavaScript", "PHP"]

aleatorio = random.choice(lenguajes)
print(aleatorio)

Python


In [ ]:
##Dado el siguiente arreglo de números: [1, 5, 8, 3, 30, 9, 13] Imprimir en pantalla programáticamente los números impares mayores a 3

A = [1, 5, 8, 3, 30, 9, 13]
B = []
for i in A:
  if i>3 and i%2!=0:
   B.append(i)# agregado elementos al final del arreglo
print (B)

[5, 9, 13]


In [ ]:
import numpy # arreglos
M= numpy.array([1,2,3,4,5,6,7])

print(M[1:3])
print(M[:3])
print(M[3:])
print(M[0:5:2])
M.sum()
#M.mean()
#M.min()
#M.max()


[2 3]
[1 2 3]
[4 5 6 7]
[1 3 5]


28

In [ ]:
import numpy # arreglos
A= numpy.array([1,2,3,4,5,6,7])
B= numpy.array([2,4,6,8,10,12,14])

A+B
A*B
A==B

array([False, False, False, False, False, False, False])

In [ ]:
# MATRICES
MATRIZ= numpy.array([[3,2,4,10],[15,11,7,3]])
for f in range(1):
 for c in range(2):
  print(MATRIZ[f][c])

3
2


In [ ]:
# MATRICES
MATRIZ= numpy.array([3,2,4,10])
for f in range(4):
 #for c in range(3):
  print(MATRIZ[f])

3
2
4
10


In [ ]:
import numpy # matrices
lista= [[3,2,4,10],[15,11,7,3]]
matriz=numpy.array(lista)
matriz

array([[ 3,  2,  4, 10],
       [15, 11,  7,  3]])

In [ ]:
# operaciones con matrices
import numpy # matrices
MATRIZ= numpy.array([[3,2,4,10],[15,11,7,3]])
for f in range(2):
 for c in range(3):
  print(MATRIZ[f][c])
print("")
print(MATRIZ[1,2])

3
2
4
15
11
7

7


In [ ]:
# MATRICES
MATRIZ= numpy.array([1,2,3,4])
for f in range(2):
  print(MATRIZ[f])

1
2
